language: go
go_import_path: github.com/grokify/gotilla
go:
  - 1.5.3
  - 1.4.3
  - tip
sudo: true
before_install:
  - sudo apt-get update -qq > apt-get.out 2>&1  || (cat apt-get.out && exit 1)
  - sudo apt-get install libgmp-dev -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
  - pip install codecov
install:
  - go get -t -v ./...
script:
  - go test -v ./...
after_success:
  - codecov